#define MG_ENABLE_LWIP 1
#define MG_ENABLE_PACKED_FS 1
#define MG_ARCH MG_ARCH_PICOSDK
//#define MG_OTA MG_OTA_PICOSDK

#define MG_ENABLE_TCPIP 0
#define MG_ENABLE_DRIVER_PICO_W 0
#define MG_ENABLE_DRIVER_W 0
#define MG_IO_SIZE 2048

